import React from "react";
// const dummyData = [];
const dummyData = [
  {
    // company_logo: facebook,
    slug: "ISLAMI COMMERCIAL INSURANCE CO.LTD",
    cutoffdate: "10/Nov/2022",
    minappamount: "10,000",
    totalshare: "2,02,61,106",
    eps: "1.82",
    nav: "20.96",
    rate: "10",
    type: "ORDINARY SHARE",
    status: "ongoing_ipo",
    listedon: "dse and cse",
    listprice: "n/a",
    offerprice: "10.00",
    listgain: "n/a",
    startdate: "11/may/2015",
    enddate: "19/may/2015",
    couponrate: "n/a",
    plateform: "Main Plateform",
    mininvest: "10,000",
    descriptionfirst:
      "When a company offers its shares for the first time, it is called an IPO or an Initial Public Offering. During this process, the company offers its shares to the general public and this entire process is carried out through the primary market.",
    descriptionsecond:
      "It simply means that through IPOs, the company collects funds which it uses to grow the business or to pay off any heavy debts. Through the IPO, an unlisted company becomes listed in the stock market",
    org: "Fortune Group",
    founded: "Fortune Group",
    director: "Fortune Group",
  },
  {
    // company_logo: facebook,
    slug: "ISLAMI COMMERCIAL INSURANCE CO.LTD",
    cutoffdate: "10/Nov/2022",
    minappamount: "10,000",
    totalshare: "2,02,61,106",
    eps: "1.82",
    nav: "20.96",
    rate: "10",
    type: "ORDINARY SHARE",
    status: "upcoming_ipo",
    listedon: "dse and cse",
    listprice: "n/a",
    offerprice: "10.00",
    listgain: "n/a",
    startdate: "11/may/2015",
    enddate: "19/may/2015",
    couponrate: "n/a",
    plateform: "Main Plateform",
    mininvest: "10,000",
  },
  {
    // company_logo: facebook,
    slug: "ISLAMI COMMERCIAL INSURANCE CO.LTD",
    cutoffdate: "10/Nov/2022",
    minappamount: "10,000",
    totalshare: "2,02,61,106",
    eps: "1.82",
    nav: "20.96",
    rate: "10",
    type: "ORDINARY SHARE",
    status: "upcoming_ipo",
    listedon: "dse and cse",
    listprice: "n/a",
    offerprice: "10.00",
    listgain: "n/a",
    startdate: "11/may/2015",
    enddate: "19/may/2015",
    couponrate: "n/a",
    plateform: "Main Plateform",
    mininvest: "10,000",
  },
  {
    // company_logo: facebook,
    slug: "ISLAMI COMMERCIAL INSURANCE CO.LTD",
    cutoffdate: "10/Nov/2022",
    minappamount: "10,000",
    totalshare: "2,02,61,106",
    eps: "1.82",
    nav: "20.96",
    rate: "10",
    type: "ORDINARY SHARE",
    status: "upcoming_ipo",
    listedon: "dse and cse",
    listprice: "n/a",
    offerprice: "10.00",
    listgain: "n/a",
    startdate: "11/may/2015",
    enddate: "19/may/2015",
    couponrate: "n/a",
    plateform: "Main Plateform",
    mininvest: "10,000",
  },
  {
    // company_logo: facebook,
    slug: "ISLAMI COMMERCIAL INSURANCE CO.LTD",
    cutoffdate: "10/Nov/2022",
    minappamount: "10,000",
    totalshare: "2,02,61,106",
    eps: "1.82",
    nav: "20.96",
    rate: "10",
    type: "ORDINARY SHARE",
    status: "closed_ipo",
    listedon: "dse and cse",
    listprice: "n/a",
    offerprice: "10.00",
    listgain: "n/a",
    startdate: "11/may/2015",
    enddate: "19/may/2015",
    couponrate: "n/a",
    plateform: "Main Plateform",
    mininvest: "10,000",
  },
  {
    // company_logo: facebook,
    slug: "ISLAMI COMMERCIAL INSURANCE CO.LTD",
    cutoffdate: "10/Nov/2022",
    minappamount: "10,000",
    totalshare: "2,02,61,106",
    eps: "1.82",
    nav: "20.96",
    rate: "10",
    type: "ORDINARY SHARE",
    status: "closed_ipo",
    listedon: "dse and cse",
    listprice: "n/a",
    offerprice: "10.00",
    listgain: "n/a",
    startdate: "11/may/2015",
    enddate: "19/may/2015",
    couponrate: "n/a",
    plateform: "Main Plateform",
    mininvest: "10,000",
  },

  {
    // company_logo: facebook,
    slug: "ISLAMI COMMERCIAL INSURANCE CO.LTD",
    cutoffdate: "10/Nov/2022",
    minappamount: "10,000",
    totalshare: "2,02,61,106",
    eps: "1.82",
    nav: "20.96",
    rate: "10",
    type: "ORDINARY SHARE",
    status: "recent_ipo",
    listedon: "dse and cse",
    listprice: "n/a",
    offerprice: "10.00",
    listgain: "n/a",
    startdate: "11/may/2015",
    enddate: "19/may/2015",
    couponrate: "n/a",
    plateform: "Main Plateform",
    mininvest: "10,000",
  },
  {
    // company_logo: facebook,
    slug: "ISLAMI COMMERCIAL INSURANCE CO.LTD",
    cutoffdate: "10/Nov/2022",
    minappamount: "10,000",
    totalshare: "2,02,61,106",
    eps: "1.82",
    nav: "20.96",
    rate: "10",
    type: "ORDINARY SHARE",
    status: "recent_ipo",
    listedon: "dse and cse",
    listprice: "n/a",
    offerprice: "10.00",
    listgain: "n/a",
    startdate: "11/may/2015",
    enddate: "19/may/2015",
    couponrate: "n/a",
    plateform: "Main Plateform",
    mininvest: "10,000",
  },
  {
    // company_logo: facebook,
    slug: "ISLAMI COMMERCIAL INSURANCE CO.LTD",
    cutoffdate: "10/Nov/2022",
    minappamount: "10,000",
    totalshare: "2,02,61,106",
    eps: "1.82",
    nav: "20.96",
    rate: "10",
    type: "ORDINARY SHARE",
    status: "recent_ipo",
    listedon: "dse and cse",
    listprice: "n/a",
    offerprice: "10.00",
    listgain: "n/a",
    startdate: "11/may/2015",
    enddate: "19/may/2015",
    couponrate: "n/a",
    plateform: "Main Plateform",
    mininvest: "10,000",
  },
];

export default dummyData;

