import Head from "next/head";
import Main from "./main";
import PageHead from "./pageHead";
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const pageTitle = "KSL Website";
  return (
    <>
      {/* <Head>
        <title>KSL Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head> */}
      <PageHead title={pageTitle} />
      <Main />
    </>
  );
}
